[project]
name = "csh_ldap"
version = "2.5.8"
description = "CSH LDAP ORM"
readme = "README.md"
license = "MIT"
license-files = ["LICENSE"]
authors = [
    { name = "Adam Brewer", email = "adamhb321@gmail.com" },
    { name = "Cole Stowell", email = "cole@stowell.pro" },
    { name = "Devin Matte", email = "devinmatte@gmail.com" },
    { name = "Galen Guyer", email = "galen@galenguyer.com" },
    { name = "Jordan Rodgers", email = "com6056@gmail.com" },
    { name = "Liam Middlebrook", email = "liammiddlebrook@gmail.com" },
    { name = "Marc Billow", email = "mbillow@me.com" },
    { name = "Max Meinhold", email = "mxmeinhold@gmail.com" },
    { name = "Michael Francis", email = "mikefrancis95@gmail.com" },
    { name = "Noah Hanford", email = "spaced@csh.rit.edu" },
    { name = "Tyler Allen", email = "tyler@tallen.me" },
    { name = "William Stevens", email = "contact@wastevensv.com" },
    { name = "tyler", email = "137842227+goosenotduck@users.noreply.github.com" },
]
maintainers = [{ name = "CSH RTP", email = "rtp@csh.rit.edu" }]
requires-python = ">=3.10"
classifiers = [
    "Natural Language :: English",
    "Operating System :: POSIX :: Linux",
]
dependencies = [
    "python-ldap==3.4.5",
    "srvlookup==3.0.0",
]

[project.urls]
Homepage = "https://github.com/ComputerScienceHouse/csh-ldap"

[dependency-groups]
dev = [
    "ruff>=0.13",
]

[tool.ruff]
line-length = 120

[tool.ruff.lint]
select = ["E", "W", "F", "N", "PL"]
ignore = [
    "PLW0603",  # global-statement
    "PLW2901",  # redefined-loop-name
]

[tool.ruff.lint.pylint]
max-args = 10
max-returns = 6
max-branches = 15
max-statements = 55

[build-system]
requires = ["uv_build>=0.12.15,<0.13.0"]
build-backend = "uv_build"
