"""
Generate typings/_ldap.pyi from python-ldap's C extension.

Usage: uv run python scripts/generate_stubs.py
"""

import inspect
from pathlib import Path
from types import ModuleType

import _ldap

OUTPUT: Path = Path(__file__).resolve().parent.parent / "typings" / "_ldap.pyi"

CONSTANT_TYPES: tuple[type, ...] = (bool, int, str, bytes)


def public_names(module: ModuleType) -> list[str]:
    """
    Get a module's public names.

    args:
        module (ModuleType): module to inspect

    return:
        sorted names
    """

    return sorted(name for name in dir(module) if not name.startswith("__") or name == "__version__")


def exception_lines(module: ModuleType, names: list[str]) -> list[str]:
    """
    Stub the module's exception classes.

    args:
        module (ModuleType): module to inspect
        names (list[str]): public names

    return:
        stub lines
    """

    exported: list[tuple[str, type[BaseException]]] = [
        (name, obj)
        for name in names
        if inspect.isclass(obj := getattr(module, name)) and issubclass(obj, BaseException)
    ]

    classes: list[type[BaseException]] = sorted(
        {cls for _, cls in exported}, key=lambda cls: (len(cls.__mro__), cls.__name__)
    )
    aliases: list[tuple[str, str]] = sorted((name, cls.__name__) for name, cls in exported if name != cls.__name__)

    lines = [f"class {cls.__name__}({cls.__bases__[0].__name__}): ..." for cls in classes]
    lines.extend(f"{name} = {target}" for name, target in aliases)

    return lines


def constant_lines(module: ModuleType, names: list[str]) -> list[str]:
    """
    Stub the module's constants.

    args:
        module (ModuleType): module to inspect
        names (list[str]): public names

    return:
        stub lines
    """

    return [
        f"{name}: {type(value).__name__}"
        for name in names
        if isinstance(value := getattr(module, name), CONSTANT_TYPES)
    ]


def function_lines(module: ModuleType, names: list[str]) -> list[str]:
    """
    Stub the module's functions.

    args:
        module (ModuleType): module to inspect
        names (list[str]): public names

    return:
        stub lines
    """

    return [
        f"def {name}(*args: Any, **kwargs: Any) -> Any: ..."
        for name in names
        if callable(obj := getattr(module, name)) and not inspect.isclass(obj)
    ]


def generate(module: ModuleType = _ldap) -> str:
    """
    Generate the stub file for a module.

    args:
        module (ModuleType): module to stub

    return:
        stub file contents
    """

    names: list[str] = public_names(module)

    sections: list[list[str]] = [
        [
            f"# Generated by scripts/generate_stubs.py from python-ldap {module.__version__}. Do not edit.",
            "",
            "from typing import Any",
        ],
        exception_lines(module, names),
        constant_lines(module, names),
        function_lines(module, names),
    ]

    return "\n\n".join("\n".join(section) for section in sections if section) + "\n"


def main() -> None:
    """
    Write the _ldap stub to typings/_ldap.pyi.
    """

    OUTPUT.parent.mkdir(exist_ok=True)
    OUTPUT.write_text(generate())
    print(f"Wrote {OUTPUT}")


if __name__ == "__main__":
    main()
